// Prediction rules generated by Zorro

int eqF(float);
double eq0(float);
double belowF(double,double);

int EURUSD_L(float* sig)
{
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 18;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 24;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 62;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 28;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 65;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 26;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 23;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 14;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 74;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 56;
  if(sig[4]<sig[5] && sig[5]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 80;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 19;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 35;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 69;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 36;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && eqF(sig[7]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 17;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 2;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 153;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && eqF(sig[8]-sig[11]) && sig[11]<sig[6] && sig[6]<sig[9])
    return 59;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 15;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[9]))
    return 63;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[3]) && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 120;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 29;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 11;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 67;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 2;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 42;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 37;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 94;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 31;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 8;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 67;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 0;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 55;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[7]<sig[10] && sig[10]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9])
    return 90;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 55;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 83;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 15;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 49;
  if(sig[4]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[5]) && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 5;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 101;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 10;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[9] && sig[9]<sig[6])
    return 53;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 35;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 1;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 3;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 30;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 58;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 8;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 68;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 44;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 54;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 58;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 45;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 24;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 26;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 93;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && eqF(sig[6]-sig[9]))
    return 30;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && eqF(sig[0]-sig[3]) && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 64;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 134;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 113;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 21;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 16;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 23;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[10]) && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 15;
  if(eqF(sig[1]-sig[4]) && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 111;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 59;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 3;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 56;
  if(eqF(sig[4]-sig[5]) && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 6;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 11;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 122;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 111;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 56;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 140;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 82;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 113;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 39;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 46;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 33;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 136;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 176;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 112;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 25;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 68;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 88;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 77;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 21;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[9] && eqF(sig[9]-sig[11]) && sig[11]<sig[6])
    return 23;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 122;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 4;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 94;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 75;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 105;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 80;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 47;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 68;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 6;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[9] && eqF(sig[9]-sig[11]) && sig[11]<sig[6])
    return 5;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 33;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 34;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 110;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 52;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && eqF(sig[6]-sig[11]) && sig[11]<sig[9])
    return 5;
  if(eqF(sig[1]-sig[4]) && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 71;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 4;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 9;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 12;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && eqF(sig[0]-sig[5]) && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 36;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 11;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && eqF(sig[9]-sig[11]) && sig[11]<sig[6])
    return 41;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 48;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 168;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 68;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 7;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 42;
  if(eqF(sig[4]-sig[5]) && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 57;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 111;
  if(sig[1]<sig[4] && sig[4]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 144;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && eqF(sig[0]-sig[3]) && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 2;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 110;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 60;
  if(sig[1]<sig[4] && sig[4]<sig[2] && eqF(sig[2]-sig[5]) && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 77;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 618;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 11;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 69;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 91;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[3]) && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 34;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 30;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 21;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 106;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && eqF(sig[6]-sig[9]))
    return 3;
  if(sig[4]<sig[5] && sig[5]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 24;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 11;
  return 0;
}

int EURUSD_S(float* sig)
{
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 0;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 33;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 40;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[7]<sig[10] && sig[10]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9])
    return 5;
  if(sig[1]<sig[4] && sig[4]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 17;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[10]) && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 40;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 63;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 53;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 104;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 15;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 57;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 21;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[9] && sig[9]<sig[6])
    return 58;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 142;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 47;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 40;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 62;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 49;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 65;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 36;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[7]<sig[10] && sig[10]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9])
    return 25;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 36;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 40;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 88;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 23;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 18;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 88;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 51;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 64;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 37;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 42;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[7]<sig[10] && sig[10]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9])
    return 25;
  if(sig[1]<sig[4] && sig[4]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 38;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 14;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 31;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 141;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 15;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 24;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 19;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 46;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 46;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 25;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 25;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 40;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 44;
  if(eqF(sig[1]-sig[2]) && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 83;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 34;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 51;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 85;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 54;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 26;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 26;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 10;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 1;
  if(sig[4]<sig[5] && sig[5]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 59;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 20;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 20;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 29;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 65;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[11]) && sig[11]<sig[9] && sig[9]<sig[6])
    return 111;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[10]) && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 64;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 57;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 78;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 2;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 60;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && eqF(sig[9]-sig[11]) && sig[11]<sig[6])
    return 49;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[8]) && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 78;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 63;
  if(sig[4]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[5]) && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 38;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 18;
  if(eqF(sig[4]-sig[5]) && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[8]) && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 37;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 83;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 6;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 8;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 76;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 99;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 18;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 53;
  if(eqF(sig[4]-sig[5]) && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[9] && sig[9]<sig[6])
    return 114;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 26;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 124;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 23;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 65;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 18;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && eqF(sig[6]-sig[9]))
    return 63;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 11;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 27;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[3]-sig[5]) && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[7]) && eqF(sig[7]-sig[8]))
    return 83;
  if(eqF(sig[4]-sig[5]) && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && eqF(sig[7]-sig[8]) && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 61;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[9] && eqF(sig[9]-sig[11]) && sig[11]<sig[6])
    return 3;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 45;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 99;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 52;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 96;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 75;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 8;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 53;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 121;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && eqF(sig[10]-sig[11]) && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 45;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 15;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9] && eqF(sig[9]-sig[11]))
    return 9;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 20;
  if(sig[1]<sig[4] && eqF(sig[4]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && eqF(sig[7]-sig[8]) && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 78;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 42;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 25;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 12;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 179;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 1;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 136;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 28;
  if(sig[4]<sig[5] && sig[5]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 105;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 34;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[2] && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[11]) && sig[11]<sig[9] && sig[9]<sig[6])
    return 80;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 57;
  if(sig[4]<sig[5] && sig[5]<sig[1] && eqF(sig[1]-sig[2]) && sig[2]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 74;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[0] && eqF(sig[0]-sig[5]) && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 101;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 0;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[3] && eqF(sig[3]-sig[5]) && sig[5]<sig[0] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[6] && eqF(sig[6]-sig[8]) && sig[8]<sig[9])
    return 44;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 100;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 20;
  if(sig[1]<sig[4] && sig[4]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 83;
  if(sig[4]<sig[1] && sig[1]<sig[5] && sig[5]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[11] && sig[11]<sig[9] && sig[9]<sig[6])
    return 37;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && eqF(sig[8]-sig[9]) && sig[9]<sig[6])
    return 20;
  if(sig[4]<sig[5] && sig[5]<sig[2] && eqF(sig[2]-sig[2]) && eqF(sig[2]-sig[2]) && sig[2]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 112;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 76;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[0] && sig[0]<sig[5] && sig[5]<sig[3] && sig[10]<sig[7] && sig[7]<sig[8] && sig[8]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 100;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && eqF(sig[10]-sig[11]) && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 43;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[7]<sig[8] && eqF(sig[8]-sig[10]) && sig[10]<sig[6] && sig[6]<sig[11] && sig[11]<sig[9])
    return 36;
  if(sig[4]<sig[1] && eqF(sig[1]-sig[5]) && sig[5]<sig[2] && sig[2]<sig[0] && sig[0]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 80;
  if(sig[1]<sig[2] && eqF(sig[2]-sig[4]) && sig[4]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 21;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 63;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[0] && eqF(sig[0]-sig[2]) && sig[2]<sig[3] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 1;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[0] && sig[0]<sig[3] && sig[10]<sig[7] && sig[7]<sig[11] && sig[11]<sig[8] && sig[8]<sig[6] && sig[6]<sig[9])
    return 1;
  if(sig[1]<sig[4] && sig[4]<sig[2] && eqF(sig[2]-sig[5]) && sig[5]<sig[3] && sig[3]<sig[0] && sig[10]<sig[11] && sig[11]<sig[7] && sig[7]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 50;
  if(sig[4]<sig[5] && sig[5]<sig[1] && sig[1]<sig[2] && eqF(sig[2]-sig[3]) && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[11] && sig[11]<sig[8] && sig[8]<sig[9] && sig[9]<sig[6])
    return 40;
  if(sig[4]<sig[1] && sig[1]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && sig[7]<sig[10] && sig[10]<sig[8] && eqF(sig[8]-sig[11]) && sig[11]<sig[6] && sig[6]<sig[9])
    return 72;
  if(sig[1]<sig[4] && sig[4]<sig[2] && sig[2]<sig[5] && sig[5]<sig[3] && sig[3]<sig[0] && eqF(sig[7]-sig[10]) && sig[10]<sig[8] && sig[8]<sig[11] && sig[11]<sig[6] && sig[6]<sig[9])
    return 91;
  return 0;
}
